"""
Cloud object storage service.

Two interchangeable providers behind one interface:

* LocalStorageService - stores objects in a local folder. Used for
  development / offline demos. Downloads go through short-lived,
  HMAC-signed URLs served by the API, imitating cloud pre-signed URLs.

* S3StorageService - any S3-compatible object store:
  AWS S3, Supabase Storage (S3 endpoint), Cloudflare R2, MinIO,
  Backblaze B2, Google Cloud Storage (interoperability mode).
  Downloads use real pre-signed URLs generated by the provider.

Choose with STORAGE_PROVIDER=local | s3.

Object keys follow:
    assignments/assignment_001/student_003/20260925T101500Z_3f9a1c2e.pdf
The bucket is PRIVATE: nothing is publicly readable, every download
needs a signed URL that the API only issues after an authorization check.
"""

import hashlib
import hmac
import logging
import time
from abc import ABC, abstractmethod
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path
from urllib.parse import quote, urlencode

from backend.config import get_settings

logger = logging.getLogger("portal.storage")


class StorageError(Exception):
    """Raised when the object storage provider fails or is unreachable."""


class StorageNotFoundError(StorageError):
    """Raised when an object does not exist."""


@dataclass
class StoredObject:
    path: str
    size: int
    content_type: str
    checksum_sha256: str
    uri: str  # provider URI, e.g. local://... or s3://bucket/key (never a public link)


def _safe_disposition(disposition: str) -> str:
    return "inline" if disposition == "inline" else "attachment"


def content_disposition(disposition: str, download_name: str) -> str:
    # RFC 6266 / 5987 - supports non-ASCII names safely.
    ascii_name = download_name.encode("ascii", "ignore").decode() or "download"
    ascii_name = ascii_name.replace('"', "")
    return f"{_safe_disposition(disposition)}; filename=\"{ascii_name}\"; filename*=UTF-8''{quote(download_name)}"


class StorageService(ABC):
    provider_name = "abstract"

    @abstractmethod
    def upload(self, path: str, data: bytes, content_type: str) -> StoredObject: ...

    @abstractmethod
    def download(self, path: str) -> bytes: ...

    @abstractmethod
    def delete(self, path: str) -> None: ...

    @abstractmethod
    def exists(self, path: str) -> bool: ...

    @abstractmethod
    def generate_signed_url(
        self, path: str, download_name: str, disposition: str = "attachment", expires_in: int | None = None
    ) -> str: ...

    @abstractmethod
    def health_check(self) -> bool: ...


# ---------------------------------------------------------------------------
# Local provider (development / offline simulation of object storage)
# ---------------------------------------------------------------------------
class LocalStorageService(StorageService):
    provider_name = "local"

    def __init__(self, root: Path, secret_key: str, public_api_url: str, default_expiry: int):
        self.root = Path(root).resolve()
        self.root.mkdir(parents=True, exist_ok=True)
        self._secret = secret_key.encode("utf-8")
        self._public_api_url = public_api_url
        self._default_expiry = default_expiry

    def _resolve(self, path: str) -> Path:
        # Prevent path traversal ("../../etc/passwd") - the final path must
        # stay inside the storage root.
        full = (self.root / path).resolve()
        if self.root != full and self.root not in full.parents:
            raise StorageError("Invalid storage path")
        return full

    def upload(self, path: str, data: bytes, content_type: str) -> StoredObject:
        try:
            target = self._resolve(path)
            target.parent.mkdir(parents=True, exist_ok=True)
            tmp = target.with_suffix(target.suffix + ".part")
            tmp.write_bytes(data)
            tmp.replace(target)  # atomic rename - no half-written files
        except StorageError:
            raise
        except OSError as exc:
            raise StorageError(f"Local storage write failed: {exc}") from exc
        return StoredObject(
            path=path,
            size=len(data),
            content_type=content_type,
            checksum_sha256=hashlib.sha256(data).hexdigest(),
            uri=f"local://{path}",
        )

    def download(self, path: str) -> bytes:
        target = self._resolve(path)
        if not target.is_file():
            raise StorageNotFoundError(path)
        return target.read_bytes()

    def file_path(self, path: str) -> Path:
        target = self._resolve(path)
        if not target.is_file():
            raise StorageNotFoundError(path)
        return target

    def delete(self, path: str) -> None:
        try:
            self._resolve(path).unlink(missing_ok=True)
        except OSError as exc:
            raise StorageError(f"Local storage delete failed: {exc}") from exc

    def exists(self, path: str) -> bool:
        return self._resolve(path).is_file()

    def _signature(self, path: str, expires: int, name: str, disposition: str) -> str:
        message = f"{path}|{expires}|{name}|{disposition}".encode("utf-8")
        return hmac.new(self._secret, message, hashlib.sha256).hexdigest()

    def generate_signed_url(self, path, download_name, disposition="attachment", expires_in=None) -> str:
        disposition = _safe_disposition(disposition)
        expires = int(time.time()) + (expires_in or self._default_expiry)
        query = urlencode(
            {
                "path": path,
                "expires": expires,
                "name": download_name,
                "disposition": disposition,
                "signature": self._signature(path, expires, download_name, disposition),
            }
        )
        return f"{self._public_api_url}/api/files/signed?{query}"

    def verify_signed_request(self, path: str, expires: int, name: str, disposition: str, signature: str) -> bool:
        if expires < int(time.time()):
            return False
        expected = self._signature(path, expires, name, _safe_disposition(disposition))
        return hmac.compare_digest(expected, signature)

    def health_check(self) -> bool:
        try:
            probe = self.root / ".healthcheck"
            probe.write_text("ok")
            probe.unlink(missing_ok=True)
            return True
        except OSError:
            logger.exception("Local storage health check failed")
            return False


# ---------------------------------------------------------------------------
# S3-compatible provider (AWS S3, Supabase Storage, Cloudflare R2, MinIO ...)
# ---------------------------------------------------------------------------
class S3StorageService(StorageService):
    provider_name = "s3"

    def __init__(self, bucket, region, endpoint_url, access_key_id, secret_access_key, sse, default_expiry,
                 public_endpoint_url=None):
        if not bucket:
            raise RuntimeError("S3_BUCKET must be set when STORAGE_PROVIDER=s3")
        import boto3  # imported lazily so local mode does not need boto3 configured
        from botocore.config import Config

        self._bucket = bucket
        self._sse = sse
        self._default_expiry = default_expiry

        def make_client(endpoint):
            return boto3.client(
                "s3",
                region_name=region,
                endpoint_url=endpoint,  # None -> real AWS S3
                aws_access_key_id=access_key_id,  # None -> IAM role / default credential chain
                aws_secret_access_key=secret_access_key,
                config=Config(
                    signature_version="s3v4",
                    retries={"max_attempts": 3, "mode": "standard"},
                    connect_timeout=5,
                    read_timeout=30,
                    s3={"addressing_style": "path"} if endpoint else {},
                ),
            )

        self._client = make_client(endpoint_url)
        # Pre-signed URLs must use a hostname the BROWSER can reach. When the
        # API talks to storage over an internal name (e.g. http://minio:9000
        # inside Docker), sign with the public endpoint instead.
        self._signer = make_client(public_endpoint_url) if public_endpoint_url else self._client

    def _wrap(self, exc: Exception, action: str) -> StorageError:
        from botocore.exceptions import ClientError

        if isinstance(exc, ClientError) and exc.response.get("Error", {}).get("Code") in {"NoSuchKey", "404"}:
            return StorageNotFoundError(action)
        logger.error("S3 %s failed: %s", action, exc)
        return StorageError(f"Object storage {action} failed")

    def upload(self, path: str, data: bytes, content_type: str) -> StoredObject:
        checksum = hashlib.sha256(data).hexdigest()
        extra = {"ContentType": content_type, "Metadata": {"sha256": checksum}}
        if self._sse:
            extra["ServerSideEncryption"] = self._sse  # encryption at rest, e.g. "AES256"
        try:
            self._client.put_object(Bucket=self._bucket, Key=path, Body=data, **extra)
        except Exception as exc:  # noqa: BLE001
            raise self._wrap(exc, "upload") from exc
        return StoredObject(path=path, size=len(data), content_type=content_type,
                            checksum_sha256=checksum, uri=f"s3://{self._bucket}/{path}")

    def download(self, path: str) -> bytes:
        try:
            return self._client.get_object(Bucket=self._bucket, Key=path)["Body"].read()
        except Exception as exc:  # noqa: BLE001
            raise self._wrap(exc, "download") from exc

    def delete(self, path: str) -> None:
        try:
            self._client.delete_object(Bucket=self._bucket, Key=path)
        except Exception as exc:  # noqa: BLE001
            raise self._wrap(exc, "delete") from exc

    def exists(self, path: str) -> bool:
        try:
            self._client.head_object(Bucket=self._bucket, Key=path)
            return True
        except Exception:  # noqa: BLE001
            return False

    def generate_signed_url(self, path, download_name, disposition="attachment", expires_in=None) -> str:
        try:
            return self._signer.generate_presigned_url(
                "get_object",
                Params={
                    "Bucket": self._bucket,
                    "Key": path,
                    "ResponseContentDisposition": content_disposition(disposition, download_name),
                },
                ExpiresIn=expires_in or self._default_expiry,
            )
        except Exception as exc:  # noqa: BLE001
            raise self._wrap(exc, "sign") from exc

    def health_check(self) -> bool:
        try:
            self._client.head_bucket(Bucket=self._bucket)
            return True
        except Exception:  # noqa: BLE001
            logger.exception("S3 health check failed")
            return False


@lru_cache
def get_storage_service() -> StorageService:
    """Factory: pick the provider from STORAGE_PROVIDER (cached singleton)."""
    settings = get_settings()
    if settings.storage_provider == "s3":
        logger.info("Using S3-compatible object storage (bucket=%s)", settings.s3_bucket)
        return S3StorageService(
            bucket=settings.s3_bucket,
            region=settings.s3_region,
            endpoint_url=settings.s3_endpoint_url,
            access_key_id=settings.s3_access_key_id,
            secret_access_key=settings.s3_secret_access_key,
            sse=settings.s3_server_side_encryption,
            default_expiry=settings.signed_url_expire_seconds,
            public_endpoint_url=settings.s3_public_endpoint_url,
        )
    if settings.storage_provider != "local":
        raise RuntimeError(f"Unknown STORAGE_PROVIDER '{settings.storage_provider}' (use 'local' or 's3')")
    logger.info("Using local object storage at %s", settings.local_storage_dir)
    return LocalStorageService(
        root=settings.local_storage_dir,
        secret_key=settings.secret_key,
        public_api_url=settings.public_api_url,
        default_expiry=settings.signed_url_expire_seconds,
    )
